version: '3.8'
services:
  expo:
    build: .
    ports:
      - "8081:8081"  # Metro Bundler
      - "19000:19000" # Expo DevTools
      - "19001:19001" # Expo Debugging
      - "19002:19002" # Expo Debugging
    volumes:
      - .:/app  # Sync local files with container
    stdin_open: true
    tty: true
